### ISSUE TITLE
Dashboard/landing-page for articles (via Murali)

### ISSUE THREAD

**Issue by prabuvenkat** [prabuvenkat/dc-issues#9]

**Comment by prabuvenkat** [comment]
Landing page will be latest 'n' articles (simplest case: n=1). 

Images inside an article will **not** show up in the landing page -- website will focus on minimal graphics. the only graphics planned at the moment are: 

- photo-gallery (pulled from DC facebook account)
- cover images of youtube videos

**Comment by prabuvenkat** [comment]
Displaying no images, or displaying the text of only the latest feature will not be a good idea-- as it will be monotonous and will not keep readers engaged or interested. 

I suggest we display at least one image (that of the most recent article) on the front page. I also suggest we display title and excerpt for 'n' (5?) recent articles in the landing page. We should also not display the recent article in complete on the front page.

**Comment by dharmaTj** [comment]
Hi Prabu

The idea is to let users read as soon as they land on the home page, without any distraction. If they like the content, they will look for more.

A simple wordpress blog like and clearly legible way where you can't miss the words, like this: https://oireachtasretort.ie/

Each article can have a small image (we will most likely have the directly playable video here anyway) like in the above page, and like you said, to make it easy for the users to find other features, instead of the main stationary image, you can do it like before, a scrolling of 5 latest features. But this should not dominate the latest feature text below. The clean look of the above example wordpress site is prefered. 

Ravi can add more on this.

**Comment by ravidalit** [comment]
Dear I dont have a particular opinion on the above said matter. I can only comment after seeing the sample. So both of you can pardon me, if I give suggestion after seeing the final home page. Certainly I wont ask to rework completely. 

I like kafila, scroll, including prabhu's past and the present. If dharma's suggestion can get more attention, as of now I dont mind in any design.

**Comment by prabuvenkat** [comment]
Finalizing on a simple listing of latest posts with thumbnails.
